### ISSUE TITLE
bug: Missing dependency

### ISSUE THREAD

**Issue by leonardo-melhor-envio** [harlan-zw/nuxt-simple-robots#4]
### Describe the bug

Unable to install and run the project.
after install i´ve tryed to run but i got this error.
i had look inside node modules folder and for some reason the dependency wasnt there.
Has it been removed from nuxt?

```
4:06:29 PM [vite] Internal server error: Failed to resolve import "@vueuse/head" from "node_modules/nuxt-simple-robots/dist/runtime/composables/defineRobotMeta.mjs?v=873cf189". Does the file exist?
  Plugin: vite:import-analysis
  File: /workspace/repo/node_modules/nuxt-simple-robots/dist/runtime/composables/defineRobotMeta.mjs?v=873cf189:2:32
  1  |  import { useNuxtApp } from '#app';
  2  |  import { useServerHead } from "@vueuse/head";
     |                                 ^
  3  |  import { indexable, robotsDisabledValue, robotsEnabledValue } from "#nuxt-simple-robots/config";
  4  |  export function defineRobotMeta() {
      at formatError (file:///workspace/repo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
      at TransformContext.error (file:///workspace/repo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
      at normalizeUrl (file:///workspace/repo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37145:33)
      at async TransformContext.transform (file:///workspace/repo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37278:47)
      at async Object.transform (file:///workspace/repo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:30)
      at async loadAndTransform (file:///workspace/repo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:29)
```

**Comment by harlan-zw** [comment]
Hey @leonardo-melhor-envio 

Thanks for the issue. I've pushed up 1.0.4 which should fix this issue
